name: alternative_gallery
description: A security online gallery using Flutter and Firebase

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  firebase_storage: ^3.0.6
  google_sign_in: ^4.0.7
  scoped_model: ^1.0.1
  crypto: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true